CATEGORY_GENERAL = "general"
CATEGORY_REALTIME = "realtime"
CATEGORY_CAMERA = "camera"
CATEGORY_TASK = "task"
CATEGORY_MIXED = "mixed"
INTENT_OPEN = "open"
INTENT_PLAY = "play"
INTENT_CAMERA = "camera"
INTENT_OPEN_WEBCAM = "open webcam"
INTENT_CLOSE_WEBCAM = "close webcam"
INTENT_GENERATE_IMAGE = "generate image"
INTENT_CONTENT = "content"
INTENT_GOOGLE_SEARCH = "google search"
INTENT_YOUTUBE_SEARCH = "youtube search"
INTENT_GMAIL_INBOX = "gmail inbox"
INTENT_GMAIL_UNREAD = "gmail unread"
INTENT_CALENDAR_LIST = "calendar list"
INTENT_CALENDAR_SEARCH = "calendar search"
INTENT_CALENDAR_CREATE = "calendar create"
INTENT_CALENDAR_DELETE = "calendar delete"
INTENT_DRIVE_SEARCH = "drive search"
INTENT_DRIVE_UPLOAD = "drive upload"
INTENT_DRIVE_LIST = "drive list"
INTENT_CHAT = "chat"

HEAVY_INTENTS = {INTENT_GENERATE_IMAGE, INTENT_CONTENT}

INSTANT_INTENTS = {
    INTENT_OPEN, INTENT_PLAY, INTENT_CAMERA,
    INTENT_OPEN_WEBCAM, INTENT_CLOSE_WEBCAM,
    INTENT_GOOGLE_SEARCH, INTENT_YOUTUBE_SEARCH,
    INTENT_GMAIL_INBOX, INTENT_GMAIL_UNREAD,
    INTENT_CALENDAR_LIST, INTENT_CALENDAR_SEARCH,
    INTENT_CALENDAR_CREATE, INTENT_CALENDAR_DELETE,
    INTENT_DRIVE_SEARCH, INTENT_DRIVE_UPLOAD, INTENT_DRIVE_LIST,
}

ROUTE_TO_INTENT = {
    "open": INTENT_OPEN,
    "play": INTENT_PLAY,
    "camera": INTENT_CAMERA,
    "open_webcam": INTENT_OPEN_WEBCAM,
    "close_webcam": INTENT_CLOSE_WEBCAM,
    "generate_image": INTENT_GENERATE_IMAGE,
    "content": INTENT_CONTENT,
    "google_search": INTENT_GOOGLE_SEARCH,
    "youtube_search": INTENT_YOUTUBE_SEARCH,
    "gmail_inbox": INTENT_GMAIL_INBOX,
    "gmail_unread": INTENT_GMAIL_UNREAD,
    "calendar_list": INTENT_CALENDAR_LIST,
    "calendar_search": INTENT_CALENDAR_SEARCH,
    "calendar_create": INTENT_CALENDAR_CREATE,
    "calendar_delete": INTENT_CALENDAR_DELETE,
    "drive_search": INTENT_DRIVE_SEARCH,
    "drive_upload": INTENT_DRIVE_UPLOAD,
    "drive_list": INTENT_DRIVE_LIST,
    "general": INTENT_CHAT,
    "realtime": INTENT_CHAT,
}
